
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http
  namespace: footnotes
spec:
  parentRefs:
  - name: my-gateway-istio
    namespace: footnotes
  # hostnames: ["footnotes.com"]
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /api/Auth
    backendRefs:
    - name: svc-iam
      port: 8001